name: Upload code coverage report

on:
    push:
      branches: [main]

    pull_request:
      branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.30.2
      - name: Create coverage files
        run: |
          deno test --allow-all --unstable --coverage=coverage
          deno --unstable coverage ./coverage --lcov > coverage.lcov
      - name: Collect coverage
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.lcov
